### ISSUE TITLE
hooks do not work for tv channel buttons when tv is off

### ISSUE THREAD

**Issue by machineonamission** [Simon34545/lginputhook#14]
I want to remap the "Sling" button on my magic remote to open YouTube Ad Free. When the TV is on, this works fine. But the tv channel buttons can wake the tv and when that happens the hooks are ignored.
For when the TV is truly powered off (Quick Start+ is off or power is lost or TV crashes) then that probably isn't possible to hook into it fast enough to redirect. But when Quick Start+ is on (the default behavior), the TV doesn't truly power off, and I theorize that the hooks might be able to work in this state.

**Comment by Simon34545** [comment]
Sorry for the late response, but no, this still isn't possible, as when Quick Start+ is on the tv basically suspends everything running when turned off.
