### ISSUE TITLE
rebind key with app launch

### ISSUE THREAD

**Issue by exalented** [Simon34545/lginputhook#2]
This app is awesome!
It would be a luxury to be able to rebind a button on the magic remote to launch another app by ID rather than use a command like the following:
`luna-send -n 1 -f luna://com.webos.service.applicationManager/launch '{"id":"org.jellyfin.webos"}'`

**Comment by Simon34545** [comment]
Do you mean having another action `launch`, which uses just an app id for launching?

**Comment by exalented** [comment]
Yes

**Comment by Simon34545** [comment]
i think this should be doable

**Comment by Simon34545** [comment]
This should be working in the latest release now.
