### ISSUE TITLE
Replace button with TV functions

### ISSUE THREAD

**Issue by Arstidir** [Simon34545/lginputhook#3]
Thank you for this app!
Is it possible to replace a button with TV functions that are not tied to a specific button? I would love to have a button with the function "turn off screen".

**Comment by Simon34545** [comment]
yes, you can do this by setting the action to execute
the command to turn off the screen is:
`luna-send -n 1 "luna://com.webos.service.tvpower/power/turnOffScreen" '{}'``

https://webostv.developer.lge.com/develop/references/luna-service-introduction

any luna service can be called with `luna-send -n 1 "luna://serviceName/method" '{...parameters}'``
