### ISSUE TITLE
Button IDs

### ISSUE THREAD

**Issue by Avdicc** [Simon34545/lginputhook#5]
I have my lg magic remote broken ok/scroll wheel
I wonder if you know ids for scroll up and scroll down slider

**Comment by Simon34545** [comment]
Maybe try these keycodes:
`UP          103`
`DOWN        108`

**Comment by Avdicc** [comment]
> Maybe try these keycodes: `UP 103` `DOWN 108`

103 and 108 are up and down buttons, the are working, but i cant find scroll wheel buttons

**Comment by Simon34545** [comment]
Perhaps `8` and `9` would work?

**Comment by kryptiko** [comment]
My LG Magic Remote power button is broken and I can't seem to find the ID to remap it. Any idea?

**Comment by Simon34545** [comment]
Try `116`

If anyone has additional questions about button IDs, check these two lists for the button you want first.
https://gist.github.com/Simon34545/31c528bfe8540880936fc4c580723a02
https://gist.github.com/Simon34545/fc5c91e0456789dd7a56a947c1148939
