### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by sonicpacific** [Simon34545/lginputhook#7]
I installed it on a LG C2 with "https://github.com/webosbrew/dev-manager-desktop/releases" and it won't open
I got this message :

Checking for root
Failed to check for root
(-1): Denied method call "getConfiguration" for category "/"

**Comment by Simon34545** [comment]
Are you rooted?

**Comment by sonicpacific** [comment]
oh no it say "unelevated". Sorry I am new to all this. How can I switch to "elevated" ?

**Comment by Simon34545** [comment]
You need to root your tv.
